# Generated by Django 4.2.5 on 2023-11-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smsapi', '0002_enrolments'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolments',
            name='mark',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
