# Generated by Django 4.2.5 on 2023-11-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smsapi', '0003_enrolments_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Smsapi.students'),
        ),
    ]
