# Generated by Django 4.2.5 on 2023-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smsapi', '0004_alter_courses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
